version: '3'
services:
  postgres:
    build:
      context: database/
    environment:
      POSTGRES_DB: raw_soccer
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
        
    restart: always
